export interface Device {
    id?: number;          // Optional, since it's generated by the backend
    name: string;
    device_type: string;  // Adjust type if needed
    ip_address?: string;  // Optional, depending on your needs
    client_id: number;    // Adjust according to your backend requirements
  }
  